name: Auto-merge Immelancholy PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  Immelancholy:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'Immelancholy' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Immelancholy PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
